version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    container_name: otus-highload-api
    ports:
      - "8000:8000"

  # The database service remains unchanged
  database:
    image: postgres:15
    container_name: otus-highload-db
    hostname: otus-highload-db
    expose: 
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: agoodpassword
      POSTGRES_USER: userdb
      POSTGRES_DB: rocketdb
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  pgdata: {}
  cargo-cache: {}  # Optional: Cache the cargo registry
