version: '3'

services:
    api:
        build: ./api
        container_name: otus-highload-api
        ports:
            - 8000:8000
        volumes:
            - ./api:/usr/src/app
        links:
            - database
    frontend:
        build: ./frontend
        container_name: otus-highload-frontend
        hostname: otus-highload-frontend
        ports:
            - 8080:8080
        command: "npm run dev"
        links:
            - api
    database:
        image: postgres:15
        container_name: otus-highload-db
        hostname: otus-highload-db
        expose: 
            - 5432
        volumes:
            - pgdata:/var/lib/postgresql/data/pgdata
        environment:
            POSTGRES_PASSWORD: agoodpassword    # put your superuser database password this here
            POSTGRES_USER: userdb
            POSTGRES_DB: rocketdb
            PGDATA: /var/lib/postgresql/data/pgdata

# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
    pgdata: {}