version: '3.9'

services:
  api:
    build:
      context: ./api
      network: host
    container_name: otus-highload-api
    ports:
      - 8000:8000
    volumes:
      - ./api:/usr/src/app
      - cargo-cache:/usr/local/cargo/registry
      - cargo-target:/usr/src/app/target
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ROCKET_DATABASES=${ROCKET_DATABASES}
      - ROCKET_ADDRESS=${ROCKET_ADDRESS}
    depends_on:
      - database
  database:
    image: postgres:15
    container_name: otus-highload-db
    hostname: otus-highload-db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", 'psql -h 0.0.0.0 -p 5432 -U user -d otus_highload -c "CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, first_name VARCHAR NOT NULL, last_name VARCHAR NOT NULL, email VARCHAR NOT NULL, password VARCHAR NOT NULL, birthday VARCHAR NOT NULL, city VARCHAR NOT NULL, interests VARCHAR NOT NULL, sex VARCHAR NOT NULL)']

volumes:
  cargo-target: {}
  pgdata: {}
  cargo-cache: {}
